### ISSUE TITLE
Issues with mead package

### ISSUE THREAD

**Issue by OladimejiDurosaro** [alexander-mead/python_library#1]
Hello, please how do I install the mead package on my M1 MacBook.
Kindly assist with the steps to successfully achieve the installation on python or Anaconda.

**Comment by alexander-mead** [comment]
Thanks for your interest. Which pieces of code are you interested in using exactly? This is a collection of various modules (https://docs.python.org/3/tutorial/modules.html) that I use semi-regularly, so you don't need to install anything. You would only need to clone the repository and then 'import mead_xxx' for whatever module was useful to you.

**Comment by OladimejiDurosaro** [comment]
Thank you for your response. I intend to use the mead_general, mead_cosmology, mead_CAMB, mead_halomodel and mead_DarkQuest. I am not sure how to clone the repository, if you could please assist or direct me on how to achieve the cloning.

**Comment by alexander-mead** [comment]
This should help: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by OladimejiDurosaro** [comment]
Thank you for your help, the issue has been fixed, I eventually cloned the repository on google colab.
